embed_dim: 4
sd_vae_config:
  z_channels: 3
  res_w: 160
  res_h: 128
  in_channels: 3
  out_ch: 3
  ch: 32
  ch_mult: [ 1,2,3,4 ]  # num_down = len(ch_mult)-1
  num_res_blocks: 1
  dropout: 0.0

  loss_config:
    kl_weight: 0.00001